# Generated by Django 4.1.6 on 2023-03-09 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_from_following',
            field=models.ManyToManyField(default=None, related_name='user_posts_from_following', to='network.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(default=None, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(default=None, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
