# Generated by Django 4.1.6 on 2023-03-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_likes_alter_post_user_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=True),
        ),
    ]
