# Generated by Django 4.1.6 on 2023-03-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
